<nav>
	<ul id="main_menu" class="">
		<li class="main-menu-item menu-first menu-item-depth-0 menu-item normal_menu_item {{ \Request::url() ==  url('/') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/') }}" class="menu-link main-menu-link"><span>Home</span></a>
		</li>
		<li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/services') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/services') }}" class="menu-link main-menu-link"><span>Layanan Kami</span></a>
		<!-- <li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/templates') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/templates') }}" class="menu-link main-menu-link"><span>Template</span></a> -->
		<li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/gallery') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/gallery') }}" class="menu-link main-menu-link"><span>Gallery</span></a>
		<li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/about') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/about') }}" class="menu-link main-menu-link"><span>Tentang Kami</span></a>
		<!-- <li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/portfolio') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/portfolio') }}" class="menu-link main-menu-link"><span>Portofolio</span></a> -->
		<!-- <li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/pricing') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/pricing') }}" class="menu-link main-menu-link"><span>Pricing</span></a> -->
		<li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/news') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/news') }}" class="menu-link main-menu-link"><span>Berita</span></a>
		<li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/team') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/team') }}" class="menu-link main-menu-link"><span>Team</span></a>
		<li class="main-menu-item menu-item-depth-0 menu-item  normal_menu_item {{ \Request::url() ==  url('/contact') ? 'current-menu-item page_item page-item-1298 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor' : '' }}"><a href="{{ url('/contact') }}" class="menu-link main-menu-link"><span>Contact</span></a>
		</li>
		
	</ul>
</nav>